"""initial schema baseline

Revision ID: eb66ff3b2e62
Revises: 
Create Date: 2026-09-24 00:21:50.618934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb66ff3b2e62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre', name='categorias_nombre_key')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cuit', name='clientes_cuit_key'),
    sa.UniqueConstraint('dni', name='clientes_dni_key')
    )
    op.create_table('medios_pago',
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_medio_pago'),
    sa.UniqueConstraint('nombre', name='medios_pago_nombre_key')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=120), nullable=False),
    sa.Column('cuit_cuil', sa.String(length=20), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('cuit_cuil', name='proveedores_cuit_cuil_key')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), server_default='empleado', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("rol IN ('jefe', 'empleado')", name='usuarios_rol_check'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('dni', name='usuarios_dni_key'),
    sa.UniqueConstraint('email', name='usuarios_email_key')
    )
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='compras_id_proveedor_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='compras_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], name='productos_id_categoria_fkey'),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo_barras', name='productos_codigo_barras_key')
    )
    op.create_index('idx_productos_nombre', 'productos', ['nombre'], unique=False)
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='ventas_id_cliente_fkey'),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medios_pago.id_medio_pago'], name='ventas_id_medio_pago_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='ventas_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('compra_detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], name='compra_detalle_id_compra_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='compra_detalle_id_producto_fkey'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('venta_detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='venta_detalle_id_producto_fkey'),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], name='venta_detalle_id_venta_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_detalle')
    op.drop_table('compra_detalle')
    op.drop_table('ventas')
    op.drop_index('idx_productos_nombre', table_name='productos')
    op.drop_table('productos')
    op.drop_table('compras')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('medios_pago')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
